version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_data
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: backend_container
    ports:
      - "3005:3005"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306

volumes:
  db_data:
